# Generated by Django 4.0.6 on 2022-07-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuasa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palette',
            name='prodDate_or_rechDate',
            field=models.DateField(),
        ),
    ]
