# Generated by Django 4.0.6 on 2022-07-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuasa', '0004_palette_voltage_alter_palette_proddate_or_rechdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palette',
            old_name='quantity',
            new_name='quantity_per_palette',
        ),
        migrations.AddField(
            model_name='palette',
            name='number_of_palettes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='palette',
            name='voltage',
            field=models.FloatField(default=12.4),
        ),
    ]
