# Generated by Django 4.0.6 on 2022-07-27 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuasa', '0005_rename_quantity_palette_quantity_per_palette_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='palette',
            name='date_limite',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 20, 40, 10, 648957)),
        ),
    ]
