# Generated by Django 4.0.6 on 2022-07-27 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuasa', '0006_palette_date_limite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palette',
            name='prodDate_or_rechDate',
        ),
        migrations.AddField(
            model_name='palette',
            name='dateTransfert',
            field=models.DateField(default=datetime.datetime(2022, 7, 27, 21, 4, 41, 47791)),
        ),
        migrations.AlterField(
            model_name='palette',
            name='date_limite',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 21, 4, 41, 47791)),
        ),
    ]
