# Generated by Django 4.0.6 on 2022-07-27 19:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yuasa', '0007_remove_palette_proddate_or_rechdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palette',
            name='dateTransfert',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='palette',
            name='date_limite',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 27, 21, 6, 29, 620734)),
        ),
    ]
