# Generated by Django 4.0.6 on 2022-07-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuasa', '0008_alter_palette_datetransfert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palette',
            name='date_limite',
            field=models.DateField(),
        ),
    ]
