# Generated by Django 4.0.6 on 2022-07-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuasa', '0010_alter_palette_date_limite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Palette',
            new_name='PaletteSauron',
        ),
    ]
