# Generated by Django 4.0.6 on 2022-07-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuasa', '0011_rename_palette_palettesauron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palettesauron',
            name='date_limite',
            field=models.DateTimeField(blank=True),
        ),
    ]
