# Generated by Django 4.0.6 on 2022-07-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuasa', '0012_alter_palettesauron_date_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palettesauron',
            name='date_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
