# Generated by Django 4.0.6 on 2022-07-29 08:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yuasa', '0013_alter_palettesauron_date_limite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalettePicard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20)),
                ('date_code', models.CharField(max_length=20)),
                ('dateTransfert', models.DateField(default=django.utils.timezone.now)),
                ('voltage', models.FloatField(default=12.4)),
                ('number_of_palettes', models.IntegerField(default=1)),
                ('quantity_per_palette', models.IntegerField()),
                ('type', models.CharField(choices=[('Industrielle', 'Indus'), ('Auto standard', 'Auto'), ('Auto AGM', 'Auto Agm'), ('Moto Wet', 'Moto Wet')], max_length=20)),
                ('date_limite', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
